name: example
description: An example of how to create a basic plugin and using it.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  tachyon:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
