name: tachyon
description: A code generation building tool.
version: 0.3.1

homepage: https://github.com/spideythewebhead/tachyon
repository: https://github.com/spideythewebhead/tachyon
documentation: https://github.com/spideythewebhead/tachyon
issue_tracker: https://github.com/spideythewebhead/tachyon/issues

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  analyzer: ^6.0.0
  analyzer_plugin: ^0.11.3
  args: ^2.4.2
  dart_style: ^2.3.3
  meta: ^1.9.0
  yaml: ^3.1.2
  glob: ^2.1.2
  path: ^1.8.3
  file: ">=6.0.0 <8.0.0"
  stack_trace: ^1.10.0
  watcher: ^1.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
