name: tachyon
description: A code generation building tool.
version: 0.0.6

homepage: https://github.com/spideythewebhead/tachyon
repository: https://github.com/spideythewebhead/tachyon
documentation: https://github.com/spideythewebhead/tachyon
issue_tracker: https://github.com/spideythewebhead/tachyon/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  analyzer: ^5.13.0
  analyzer_plugin: ">=0.10.0 <1.0.0"
  args: ^2.3.1
  dart_style: ^2.2.4
  meta: ^1.8.0
  yaml: ^3.1.1
  glob: ^2.1.1
  path: ^1.8.2
  file: ">=6.0.0 <8.0.0"
  stack_trace: ^1.10.0
  watcher: ^1.0.2
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
