name: tachyon
description: A code generation building tool.
version: 0.4.0-dev.1

homepage: https://github.com/spideythewebhead/tachyon
repository: https://github.com/spideythewebhead/tachyon
documentation: https://github.com/spideythewebhead/tachyon
issue_tracker: https://github.com/spideythewebhead/tachyon/issues

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  analyzer: ">=7.0.0 <8.0.0"
  analyzer_plugin: ^0.13.0
  args: ^2.7.0
  dart_style: ^3.1.0
  meta: ^1.9.0
  yaml: ^3.1.2
  glob: ^2.1.2
  path: ^1.9.0
  file: ">=7.0.0 <8.0.0"
  stack_trace: ^1.11.1
  watcher: ^1.1.4
  pub_semver: ^2.1.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.26.3
