# Which paths to watch for file changes
file_generation_paths:
  - "lib/src/main.dart"
  - "lib/src/models/**"

# Use the package name found in "pubspec.yaml"
external_packages:
  # Can set your own packages
  my_local_package:

  # Can use 3rd party packages
  provider:
    # Can optionally provide globs to filter files
    file_generation_paths:
      - "lib/provider.dart"

generated_file_line_length: 100

# External plugins to use for code generation
plugins:
  - data_class_plugin
  - http_client_plugin
